### ISSUE TITLE
copyfile('./s_train_amazon.py', path_save_base+'/s_train_amazon'+run_id+'.py')

### ISSUE THREAD

**Issue by ShaoPengyang** [newlei/LR-GCCF#1]
”
s0
has results save path
Traceback (most recent call last):
  File "train_amazons.py", line 52, in <module>
    copyfile('./s_train_amazon.py', path_save_base+'/s_train_amazon'+run_id+'.py')
  File "/home/shaopengyang/.conda/envs/gcn/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './s_train_amazon.py'
“

**Comment by ShaoPengyang** [comment]
JUST comment it.
